### ISSUE TITLE
whistle & moan detector: get each tonal start time in seconds from beginning of read audio file.

### ISSUE THREAD

**Issue by shadiakiki1986** [TaikiSan21/PamBinaries#1]
Hello. I ran pamguard on one of the audio files on mobysound.org. I also configured it to save the results to a binary file, which I'm reading with PamBinaries. For the output of `loadPamguardBinaryFile`, how does the `startSample` field relate to the number of seconds from the start of the audio file? Is it `startSample / sampleRate = time offset in seconds`? I'm looking to get the detected whistle's starting time in seconds from the start of the audio file.

**Comment by TaikiSan21** [comment]
In short, yes it is just `startSample / sampleRate`, but there are a couple cases where this is not true. First, if that detector is being fed data from a decimator instead of the raw audio from Sound Acquisition, then the `startSample` will be in units of the decimated sample rate, not the original. Second, if you have checked the `Merge Contiguous Files` box in the settings for Sound Acquisition checked (this only appears if selecting multiple files or a folder of files - I believe it is typically _not_ recommended to check this box), then the `startSample` will count the total number of samples from the start of the first audio file processed, which can be a pain to sort out later. Hope that clears things up.

**Comment by shadiakiki1986** [comment]
Thanks!
